FROM nvcr.io/nvidia/tensorflow:23.03

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

# Install essential software
COPY scripts/pkg-install/*.sh /tmp
RUN  chmod a+x /tmp/*.sh
RUN  /tmp/essential-util.sh
RUN  /tmp/essential-net.sh
RUN  /tmp/essential-build.sh

# A) Install OpenMPI (from package)
COPY scripts/pkg-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/openmpi.sh

# B) Install and XPN (from source)
COPY scripts/src-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/xpn.sh  /usr/src/daloflow/xpn

# C) Install Horovod and SSH (from package)
COPY scripts/pkg-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/horovod-cuda.sh
 RUN  /tmp/ssh.sh

# Initial env
RUN echo 'root:daloflow' | chpasswd

RUN mkdir -p /daloflow
RUN ln -s /usr/src/daloflow /root/daloflow_src
RUN ln -s /daloflow         /root/daloflow
WORKDIR "/daloflow"

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

