FROM tensorflow/tensorflow:latest-gpu

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

# Directories
 RUN mkdir -p /daloflow
 RUN ln -s /usr/src/daloflow /root/src
 RUN ln -s /daloflow         /root/daloflow
 RUN mkdir -p  /root/bin

# Install essential software
COPY scripts/pkg-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/essential-util.sh
 RUN  /tmp/essential-net.sh
 RUN  /tmp/essential-build.sh

# A) Install OpenMPI (from package)
COPY scripts/pkg-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/openmpi.sh

# B) Install XPN (from source)
COPY scripts/src-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/xpn.sh  /usr/src/daloflow/xpn

# C) Install Horovod and SSH (from package)
COPY scripts/pkg-install/*.sh /tmp
 RUN  chmod a+x /tmp/*.sh
 RUN  /tmp/horovod.sh
 RUN  /tmp/ssh.sh

# Initial env
RUN echo 'root:daloflow' | chpasswd

WORKDIR "/daloflow"

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

